# .github/FUNDING.yml
# Enables the "Sponsor" button on the repository
# Best practice: keep 2–4 clear funding options

# GitHub Sponsors (preferred)
github: 
  - eduardomioto

# Open Collective (great for team/transparent funding)
# open_collective: perfinsights.link

# Ko-fi (easy one-off and recurring donations)
# ko_fi: perfinsights.link

# Optional extras (uncomment if actively used)
# patreon: chromeperformance
# buymeacoffee: chromeperf
